name : Upload website to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      run: npm run cy:run -- --browser chrome --env grepTags="@Envtest1",ENV="staging"
    # with:
    # - name: 
    #   args: --acl public-read --follow-symlinks --delete
    env:
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUKCET }}
      AWS_ACCESS_KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'ca-central-1'
      SOURCE_DIR: 'resume-site'